# Site settings
title: "Python Problem Solving Blog"
description: "Elegant Python solutions to coding challenges with detailed explanations"
author: "Daniel Birmajer"
email: "dbirmajer@gmail.com"
github_username: dbirmajer
url: "https://dbirmajer.github.io"
baseurl: "/python-problem-solving-blog"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true
  input: GFM
  hard_wrap: false
  # Remove the extra math_engine_opts if you had them
  

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - problems/index.md
  - about.md

# Collections for organizing problems
collections:
  problems:
    output: true
    permalink: /problems/:name/

# Custom settings
show_excerpts: true
future: true

# MathJax configuration
mathjax: true

# SEO settings
social:
  name: "dbirmajer"
  links:
    - https://github.com/dbirmajer

# Exclude problematic files
exclude:
  - "*.old"
  - ".#*"
  - "*.tmp"
  - "*.bak"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

