# Site settings
title: "Python Problem Solving Blog"
description: "Elegant Python solutions to coding challenges with detailed explanations"
author: "Daniel Birmajer"
email: "dbirmajer@gmail.com"
github_username: dbirmajer
url: "https://dbirmajer.github.io"
baseurl: "/python-problem-solving-blog"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Enable syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - problems/index.md
  - about.md

# Collections for organizing problems
collections:
  problems:
    output: true
    permalink: /:collection/:name/

# Custom settings
show_excerpts: true
future: true

# Exclude problematic files
exclude:
  - "*.old"
  - ".#*"
  - "*.tmp"
  - "*.bak"
  
# SEO settings
social:
  name: "dbirmajer"
  links:
    - https://github.com/dbirmajer
